### ISSUE TITLE
AMQP / AWS SQS

### ISSUE THREAD

**Issue by pfortin-urbn** [shicky/gocelery#13]
Can I use AMQP to talk to AWS? or is there an AWS backend in the works?
As well and example for AWS would be nice if that is an option of course.

**Comment by shicky** [comment]
Thanks for the issue.
As far as I can tell, AWS SQS does not use AMQP so it is not compatible.
I do not have access to AWS SQS.
Perhaps, I can help you get AWS SQS to work if you could give me an access.

**Comment by shicky** [comment]
Not supporting at the moment.
