### ISSUE TITLE
Use configurable logging library

### ISSUE THREAD

**Issue by Huangsir** [shicky/gocelery#15]
Use something seelog or logrus, at least we can configura the log level and log path

**Comment by shicky** [comment]
I am not sure if it is good idea to use non-standard third-party logging libraries on open-source project like gocelery.
Projects that integrates gocelery may want to have freedom to chose logging library of their own.

**Comment by Huangsir** [comment]
You can offer a method to change log config on runtime

**Comment by shicky** [comment]
Could you explain further through email? (shicky@gmail.com)
