### ISSUE TITLE
Support multiple clients

### ISSUE THREAD

**Issue by shicky** [shicky/gocelery#23]
In current implementation, `gocelery` workers consume task item from queue and discard if its not intended for them.
When there are multiple `CeleryClient`, they may consume task items intended for competing `CeleryClient` and discard all of them.

Needs to investigate `celery` implementation for the case of multiple workers on same machine.
[http://docs.celeryproject.org/en/latest/userguide/workers.html](http://docs.celeryproject.org/en/latest/userguide/workers.html)

Possible solutions:
- Instead of discarding the task item, put it back to the queue. (This may cause starvation issue)
- Peek at the task item instead of consuming and consume it only when its valid. (this may also cause issues if malformed request is pushed into the queue)

**Comment by tensor146** [comment]
Looks like this issue still was not fixed.
As I see, every worker still consuming all tasks it can consume and always acking them (and just printing "task is not registered" notice) instead of requeue'ing.
