### ISSUE TITLE
Support RabbitMQ

### ISSUE THREAD

**Issue by shicky** [shicky/gocelery#4]
Support RabbitMQ database.

**Comment by Huangsir** [comment]
+1

**Comment by shicky** [comment]
Branch amqp created.

**Comment by shicky** [comment]
AMQP broker tested and committed d4c0e323bfbf5f1c39d1ca7fef024d044000bb35
AMQP backend is not working yet.

**Comment by shicky** [comment]
Precondition Failure - durable issue with python client.

```bash
amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'durable' for queue '60334fcaf5ea4048bd143b7466708cd2' in vhost '/': received 'true' but current is 'false'
```

**Comment by shicky** [comment]
Now broker and backend fully supported. cd4f137f948b67419cfe5c2c82f3c1fb2760da8e
